apisdjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')), #Include frontend app urls
    path('spotify/', include('spotify.urls')), #Include sotify app urls
]

frontend/urls.py
from django.urls import path
from .views import index

app_name = 'frontend'

urlpatterns = [
    path('', index, name = 'index'),
]

spotify/urls.py
from django.urls import path
from .views import *

app_name = 'spotify'

urlpatterns = [
    path('get-auth-url', AuthURL.as_view(), name='get-auth-url'),
    path('redirect', spotify_callback, name='callback'),
    path('is-authenticated', IsAuthenticated.as_view(), name='is-authenticated'),
    path('get-all-tokens', ListAllTokens.as_view(), name='all-tokens'),
    path('get-current-song', CurrentSong.as_view(), name='current-song'),
    path('get-songs-history', SongsHistory.as_view(), name='songs-history'),
    path('top-artists', TopArtists.as_view(), name='top-artists'),
    path('top-tracks', TopTracks.as_view(), name='top-tracks'),
    path('current-user-info', UserInfo.as_view(), name='current-user-info'),
    path('last-saved-songs', LastSavedSongs.as_view(), name='last-saved-songs'),
    path('user-playlists', GetUserPlaylists.as_view(), name='user-playlists'),
    path('followed-artists', GetFollowedArtists.as_view(), name='followed-artists'),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, template_name="index.html")

frontend/templates/index.html
<h1>Ping</h1>
<h1>Pong!</h1>

<ol>
    <li>First step --> Authenticate: <a href="{% url "spotify:get-auth-url" %}">spotify/get-auth-url</a></li>
    <li>Check if u're authenticated: <a href="{% url "spotify:is-authenticated" %}">spotify/is-authenticated</a></li>
    <h4>Just for authenticated users.</h4>
    <li><a href="{% url "spotify:all-tokens" %}">spotify/all-tokens</a></li>
    <li><a href="{% url "spotify:current-user-info" %}">spotify/current-user-info</a></li>
    <li><a href="{% url "spotify:current-song" %}">spotify/get-current-song</a></li>
    <li><a href="{% url "spotify:songs-history" %}">spotify/songs-history</a></li>
    <li><a href="{% url "spotify:top-artists" %}">spotify/top-artists-and-genres</a></li>
    <li><a href="{% url "spotify:top-tracks" %}">spotify/top-tracks</a></li>
    <li><a href="{% url "spotify:last-saved-songs" %}">spotify/last-saved-songs</a></li>
    <li><a href="{% url "spotify:user-playlists" %}">spotify/user-playlists</a></li>
    <li><a href="{% url "spotify:followed-artists" %}">spotify/followed-artists</a></li>
</ol>